### ISSUE TITLE
GTX1050ti does not do RPM fan speed.

### ISSUE THREAD

**Issue by MaynardMiner** [falahati/NvAPIWrapper#12]
``nvapi_gpu_gettachreading`` doesn't work for GTX1050ti cards. It only does % readings.

When I remove the following:

https://github.com/falahati/NvAPIWrapper/blob/master/NvAPIWrapper/GPU/GPUCooler.cs#L26

and

https://github.com/falahati/NvAPIWrapper/blob/master/NvAPIWrapper/GPU/GPUCoolerInformation.cs#L54

``GPUCoolerInformation`` works, and you can control fans. If not, then you NVAPI_NOT_SUPPORTED errors.

You may want to consider having the Tach/RPM speed in a different lower level API method.

**Comment by falahati** [comment]
Can you double check if this card supports the new API for changing fan speed? Just follow the code execution and confirm if it uses `SetClientCoolerFanControl()` method to change the fan speed.

**Comment by MaynardMiner** [comment]
It does not.

I'm pretty sure this is the case of simply that it is a low grade card, and doesn't have a tach sensor, just like it doesn't have any built in voltage sensors.

**Comment by falahati** [comment]
It seems that I incorrectly read this as an issue for RTX2050 instead of GTX1050. What you said totally makes sense.
Thank u for reporting this. Will be fixed in the next commit when I get home.

**Comment by falahati** [comment]
Should be solved.
