### ISSUE TITLE
Add custom resolution

### ISSUE THREAD

**Issue by micodeyt** [falahati/NvAPIWrapper#13]
Hello @falahati  !

I managed to change my screen resolution thanks to your answer here (#8), 
however I'd like to add a custom resolution (as in the nvidia control panel), do you have any clue how I could do this ?

Thanks !

**Comment by falahati** [comment]
Unfortunately, these APIs are not yet supported by this wrapper. In fact, I am not even sure what APIs can be used to do so.

If [this](https://stackoverflow.com/questions/6835076/how-can-i-force-any-display-resolution-timing-i-want) answer is to be trusted, it seems that this functionality is only available in their NDA version of the NVAPI. Therefore to get our hands on these functionalities we need to reverse engineer an application that already does that and NVIDIA Control Panel is not a very good option as it does a lot of other things and this makes it hard to debug.

Some tools like this might be able to help you:
https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU

You can also rewrite this by expanding the [EDIDParser](https://github.com/falahati/EDIDParser) library I wrote to allow modifying EDID binary, but I don't recommend that. A lot of things can go wrong when overriding EDID information.

I keep this issue open in case someone could give us some hints in regard to functions available in the NDA version of NVAPI. ;)

**Comment by falahati** [comment]
`NvAPI_DISP_DeleteCustomDisplay()`, `NvAPI_DISP_EnumCustomDisplay()`, `NvAPI_DISP_RevertCustomDisplayTrial()`, `NvAPI_DISP_SaveCustomDisplay()` and `NvAPI_DISP_TryCustomDisplay()` might be relevent. I check these later.

I will accept any PR adding support for these function.

**Comment by falahati** [comment]
Added support in the latest commit. Will be published in the next release.
