### ISSUE TITLE
ScanOutInformation.EnableWarping Fails

### ISSUE THREAD

**Issue by markbokach** [falahati/NvAPIWrapper#18]
Hello, 
I've been playing around with this API for a couple of days and it does the majority of the things that I need and is very well written, thanks for that. Unfortunately I'm running into a problem with using the EnableWarping method. With the original Nuget package, the exception I get is

Type 'NvAPIWrapper.Native.Display.Structures.ScanOutWarpingV1' cannot be marshaled as an unmanaged structure, no meaningful size or offset can be computed. 

After pulling down the source and poking around I narrowed the problem down to the line in the constructor of the ScanOutWarpingV1 class

this = typeof(ScanOutWarpingV1).Instantiate<ScanOutWarpingV1>();

this throws the exception, is ignored but the same exception gets thrown when the delegate gets called. Removing each property of the ScanOutWarpingV1 class and running it again I found that the Rectangle _TextureRectangle was the culprit. I removed the [MarshalAs(UnmanagedType.LPStruct)] attribute and the ScanOutWarpingV1 class would get instantiated without errors but then when executing the delegate I received an IncompatibleStructureVersion error. So it seems like it at least is getting through to the API but fails for some reason. I downloaded the new version of the NvAPI, version 440, from the Nvidia website and used your NvAPICodeGenerator project but the structure for the ScanOutWarpingV1 looks to be the same. Any help you could provide would be appreciated. Please let me know if you have any questions. Thanks!

**Comment by falahati** [comment]
My bad, It seems that I forgot to add the `IInitializable` interface to the `Native.General.Structures.Rectangle`. I will push a commit asap. Meanwhile, you can continue with your project just by adding the interface to the class:

```C#
public struct Rectangle : IInitializable
{
```

Feel free to report any new issue you encountered with the library.

PS. 'NvAPICodeGenerator' project just generates the classes and types necessary for the NVS part of the project as of now. Converting structures automatically is a much harder thing to do.

**Comment by falahati** [comment]
Ignore the last comment. The problem is something else entirely. I will push a commit as soon as I fix it.

**Comment by falahati** [comment]
Pull the latest commit and do a rebuild. It should work now. I get a not supported exception tho that might be due to the type and the model of the GPU and therefore I cannot test the whole operation. What I can tell you that now we send the information correctly to the NVAPI library.

Since this is a change to a part of the library that is rarely used, I am not going to immediately release a new version.

**Comment by falahati** [comment]
This is not released to NuGet along with some other changes with version 0.7.2
