### ISSUE TITLE
Can I use this library to set values?

### ISSUE THREAD

**Issue by ravensorb** [falahati/NvAPIWrapper#2]
Does this library support read/write to update various settings on Nvidia cards?

**Comment by falahati** [comment]
What values are you interested in?

As it is clearly stated on the readme page of this repository, this library is still incomplete. In this stage, it can change display EDID settings, Display configuration and arrangement, and Nvidia Surround settings.

However, there is a very strong foundation to the library and you easily expand it if you find some entry points missing.

**Comment by falahati** [comment]
I am going to close this issue due to receiving no response from the issue owner.

**Comment by ravensorb** [comment]
Sorry, I got sidetracked.  The idea would be to change things like 

- GPU Clock Speed
- GPU Voltage
- GPU Memory Clock
- Fan Speed
- Min/Max Power Targets
- GPU Temp Targets

**Comment by falahati** [comment]
Not yet, unfortunately, I am going to leave this open as a feature request.

Also, you can always contribute to the project to add these functionalities. Following documentation is a good start and based on what I can see there, it seems like an easy task.
https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__gpupstate.html

**Comment by falahati** [comment]
It's now possible to change these setting using the low-level APIs:

**Overclock and overvoltage**
To get clock speed you can try the high level `GPU.PhysicalGPU.GPUPerformanceStatesInformation` property and to change these settings you should be able to use `Native.GPUApi.GetPerformanceStates20()` and `Native.GPUApi.SetPerformanceStates20()` methods.

**Pascal+ overclock and overvoltage**
In addition to the methods and properties described above; for certain GPUs including Pascal series of GPUs it is possible to retrieve and change the additional available settings. Followings are the methods that might be interesting to you:
`Native.GPUApi.GetVFPCurve()`
`Native.GPUApi.GetClockBoostLock()`
`Native.GPUApi.SetClockBoostLock()`
`Native.GPUApi.GetClockBoostTable()`
`Native.GPUApi.SetClockBoostTable()`
`Native.GPUApi.GetCoreVoltageBoostPercent()`
`Native.GPUApi.SetCoreVoltageBoostPercent()`
`Native.GPUApi.GetClockBoostMask()`
`Native.GPUApi.GetClockBoostRanges()`
`Native.GPUApi.GetCurrentVoltage()`

**Cooler (fan) control**
Full cooler control functionalities are available via the high-level API via the `GPU.PhysicalGPU.CoolerInformation` property.

**Power target**
Power target and performance cap status can be monitored using the high-level API available via the `GPU.PhysicalGPU.PerformanceControl` property.
To change these settings the following low-level methods might be used:
`Native.GPUApi.ClientPowerPoliciesGetInfo()`
`Native.GPUApi.ClientPowerPoliciesGetStatus()`
`Native.GPUApi.ClientPowerPoliciesSetStatus()`

**Thermal Targets**
Thermal target and performance cap status can be monitored using the high-level API available via the `GPU.PhysicalGPU.PerformanceControl` property.
To change these settings the following low-level methods might be used:
`Native.GPUApi.GetThermalPoliciesInfo()`
`Native.GPUApi.GetThermalPoliciesStatus()`
`Native.GPUApi.SetThermalPoliciesStatus()`

**Comment by falahati** [comment]
I am therefore closing this issue. Feel free to reopen or create a new issue if you had any question or issue with the library.
