### ISSUE TITLE
Change gamma using this (namely the gamma location in Nvidia CP)

### ISSUE THREAD

**Issue by Straafe** [falahati/NvAPIWrapper#20]
This is what I am trying to change in code: https://i.stack.imgur.com/Rxk1R.png

I know there are gamma-related methods in the Nvidia API, such as **NvAPI_VIO_SetGamma**, but I am not sure how to use them using this wrapper in C#. Is it possible? I only need to change the gamma there, not any other color settings.

**Comment by falahati** [comment]
Gamma, brightness, and contrast are controlled via the Windows API even when modified from the NVidia Control panel. There is no API in NVAPI for them. `NvAPI_VIO_SetGamma` is about NVidia Capture Cards (VIO) and has nothing to do with monitors.

Specifically for gamma, the related method is (`GetDeviceGammaRamp()`)[https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getdevicegammaramp].

**Comment by falahati** [comment]
It might also be possible to ask the monitor to change the related settings via I2C.

Take a look into the [`I2CSample.cs`](https://github.com/falahati/NvAPIWrapper/blob/master/NvAPISample/I2CSample.cs) for an example about changing the brightness by communicating with the monitor. It might be possible to modify the code to change the monitor's gamma value. I know the contrast index (`128`) but I don't have any info about the gamma. 

This might be useful:
https://cgit.freedesktop.org/~aplattner/nvidia-settings/tree/src/libXNVCtrl/NVCtrl.h?id=b27db3d10d58b821e87fbe3f46166e02dc589855#n1329

**Comment by Straafe** [comment]
Ah, ok I see. Thanks for the information. I found this wrapper and was giving it a try because I had already done some testing using **SetDeviceGammaRamp()**, but even though it appeared to run, my monitor's gamma never changed. I'd assumed it was because I had to deal with gamma through Nvidia instead, but now I see I was wrong. I'll be doing some more testing using the information you've provided, thanks again.

**Comment by falahati** [comment]
I recently wrote a function to change the gamma ramp similar to what NVidia Control Panel send to the API. Check it out:

```C#

```C#
private static ushort[] CalculateLUT(double brightness = 0.5, double contrast = 0.5, double gamma = 1)
{
    const int dataPoints = 256;

    // Limit gamma in range [0.4-2.8]
    gamma = Math.Min(Math.Max(gamma, 0.4), 2.8);

    // Normalize contrast in range [-1,1]
    contrast = (Math.Min(Math.Max(contrast, 0), 1) - 0.5) * 2;

    // Normalize brightness in range [-1,1]
    brightness = (Math.Min(Math.Max(brightness, 0), 1) - 0.5) * 2;

    // Calculate curve offset resulted from contrast
    var offset = contrast > 0 ? contrast * -25.4 : contrast * -32;

    // Calculate the total range of curve
    var range = (dataPoints - 1) + offset * 2;

    // Add brightness to the curve offset
    offset += brightness * (range / 5);

    // Fill the gamma curve
    var result = new ushort[dataPoints];
    for (var i = 0; i < result.Length; i++)
    {
        var factor = (i + offset) / range;

        factor = Math.Pow(factor, 1 / gamma);

        factor = Math.Min(Math.Max(factor, 0), 1);

        result[i] = (ushort)Math.Round(factor * ushort.MaxValue);
    }

    return result;
}
```
```

**Comment by falahati** [comment]
Use this along with `SetDeviceGammaRamp()` Windows API to change the gamma, brightness, and/or contrast.

**Comment by Straafe** [comment]
That looks awesome, will check it out!

**Comment by incheon-kim** [comment]
> I recently wrote a function to change the gamma ramp similar to what NVidia Control Panel sends to the API. Check it out:
> 
> ```cs
> private static ushort[] CalculateLUT(double brightness = 0.5, double contrast = 0.5, double gamma = 1)
> {
>     const int dataPoints = 256;
> 
>     // Limit gamma in range [0.4-2.8]
>     gamma = Math.Min(Math.Max(gamma, 0.4), 2.8);
> 
>     // Normalize contrast in range [-1,1]
>     contrast = (Math.Min(Math.Max(contrast, 0), 1) - 0.5) * 2;
> 
>     // Normalize brightness in range [-1,1]
>     brightness = (Math.Min(Math.Max(brightness, 0), 1) - 0.5) * 2;
> 
>     // Calculate curve offset resulted from contrast
>     var offset = contrast > 0 ? contrast * -25.4 : contrast * -32;
> 
>     // Calculate the total range of curve
>     var range = (dataPoints - 1) + offset * 2;
> 
>     // Add brightness to the curve offset
>     offset += brightness * (range / 5);
> 
>     // Fill the gamma curve
>     var result = new ushort[dataPoints];
>     for (var i = 0; i < result.Length; i++)
>     {
>         var factor = (i + offset) / range;
> 
>         factor = Math.Pow(factor, 1 / gamma);
> 
>         factor = Math.Min(Math.Max(factor, 0), 1);
> 
>         result[i] = (ushort)Math.Round(factor * ushort.MaxValue);
>     }
> 
>     return result;
> }
> ```

This code saved my day! Brilliant! Thanks.

**Comment by marsarCV** [comment]
When I use the above code along with SetDeviceGammaRamp() function, it tries to change the display momentarily and then reverts back. I think it might be due to the way I am accessing the display handle or something else but not because of the CalculateLUT() function. Can you see what is the problem?

` 
public class Win32
    {
        // Get Display control
        [DllImport("user32")]
        public static extern IntPtr GetDC(IntPtr hWnd);

        // Get Display control
        [DllImport("user32")]
        public static extern IntPtr ReleaseDC(IntPtr n, IntPtr hWnd);

        // Ramp function
        [DllImport("gdi32")]
        public static extern bool GetDeviceGammaRamp(IntPtr hDC, [Out] ushort[] lpRamp);
        
        [DllImport("gdi32")]
        public static extern bool GetGammaRamp(IntPtr hDC, [Out] ushort[] lpRamp);

        [DllImport("gdi32")]
        public static extern bool SetDeviceGammaRamp(IntPtr hDC, ushort[] lpRamp);
        
        [DllImport("gdi32")]
        public static extern bool SetGammaRamp(IntPtr hDC, ushort[] lpRamp);

        [DllImport("gdi32")]
        public static extern bool SupportsFullscreenGamma();

        public static IntPtr hDC;
        public static ushort[] originalRamps;
    }
    
    
        class Program
    {
        // Color Matchingg dictionary
        static void Main(string[] args)
        {

            // Control the display brightness, contrast and gamma
            ushort[] newValues = CalculateLUT(0.1, 0.4, 1.1);
            Win32.hDC = Win32.GetDC(IntPtr.Zero);
            Win32.originalRamps = new ushort[256];
            Win32.GetDeviceGammaRamp(Win32.hDC, Win32.originalRamps);

            // Change the brightness, gamma and contrast
            Win32.SetDeviceGammaRamp(Win32.hDC, newValues);

            Win32.ReleaseDC(IntPtr.Zero, Win32.hDC);
         }
   }`

**Comment by falahati** [comment]
My [WindowsDisplayAPI](https://github.com/falahati/WindowsDisplayAPI) library can be used to get information about monitors and manipulate their config including the GammaRamp. Take a look. You are probably interested in `Display.GamaRamp` property.

**Comment by marsarCV** [comment]
Great! It worked, Thanks. I also want to extract the current values for brightness, contrast, gamma for the display. Is there any property in the API for this?

Can gamma ramp values be decomposed some way to get these values?

**Comment by falahati** [comment]
No, unfortunately, the algorithm used is one way. NVidia control panel keeps the raw values in the registry for UI porpuses, otherwise guessing the values from the ramp is not practical.

**Comment by LikeyX** [comment]
> My [WindowsDisplayAPI](https://github.com/falahati/WindowsDisplayAPI) library can be used to get information about monitors and manipulate their config including the GammaRamp. Take a look. You are probably interested in `Display.GamaRamp` property.

Hey, did the Diplay.GammaRamp Property and Display.IsPrimary() Method removed?

**Comment by falahati** [comment]
@LikeyX no, but I think they are on the prerelease package.
