### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Narko22** [falahati/NvAPIWrapper#23]
Hello,
I am an owner of a Titan RTX and I am doing 3D rendering.
I found this place while searching for how to control my fan speeds while operating the GPU at TCC mode.
I have seen a few discussions here and I think I am understanding that you found how to achieve what I am looking for.
But I haven't seen any friendly tutorials from beginning to finish on how to install, run, and use this tool or whatever it is named :(

Please if anyone can help me out here or refer me to the right place, I would very much appreciate it! It will help me a ton!

**Comment by Narko22** [comment]
Using Windows 10 Pro

**Comment by falahati** [comment]
Hey @Narko22,
This is not a tool but rather a library that can be used by other people to create such tools.

So even tho this project does all the heavy lifting, it doesn't have a user interface for end-users and it will never do. So unless you know how to program or find another tool that made using this library, you are unfortunately out of luck.

You should have no problem finding someone to make a tool for such an application as it should be trivial. Now I personally never tested the library with TCC drivers, but it should work based on material I have read while making this library.

**Comment by falahati** [comment]
For fan control, I just found this tool that someone wrote using this library, check it out:
https://github.com/MaynardMiner/SWARM/tree/master/build/apps/nvfans

@MaynardMiner is the developer of this tool.
