### ISSUE TITLE
Faking NVIDIA Surround API information?

### ISSUE THREAD

**Issue by Jademalo** [falahati/NvAPIWrapper#24]
When running Nvidia surround, certain games are given API information regarding the size of each monitor. This allows them to constrain the UI of a game to the middle monitor while spanning the game across all 3 monitors.

Since Nvidia surround is such a huge pain, I've started using a method with an AutoHotKey script to resize games in borderless windowed mode to the full triplewide resolution. This works well, but has the downside of the games not having the API information to constrain the UI to the middle monitor.

Using this, is it possible to fake that surround API information in order to constrain the UI in a given game?

I believe page 14 of this document is how it's generally implemented, and what I want to try and spoof - http://developer.download.nvidia.com/whitepapers/2010/SurroundBestPracticesGuide.pdf

Thanks

**Comment by falahati** [comment]
Hey,

No, you can't fake this information for a specific application with this library. 
Doing so is a lot of work. I suggest not even trying that. You need to hook a ton of methods in DirectX and probably elsewhere.

I have a project that supposed to make switching to surround setups easier; available here:
https://github.com/falahati/HeliosDisplayManagement/

It is still in development and some functionalities like `Edit` doesn't work yet, but if you save your profiles, it can switch between them relatively fast.

**Comment by Jademalo** [comment]
Alright, no problem, thanks for letting me know!

I've used Helios in the past, and while it's certainly better than switching with the built in Nvidia control panel, the main issues I have are with how Surround is designed in the first place. Since I have 6 monitors attached to this PC, when I try to set up a surround mosaic I just have no end of issues and instabilities. 
That's not an issue with Helios though, that's just the driver.

My little spanning script has been super useful for games where I can either manually tweak the UI such as World of Warcraft, or games without an edge aligned UI. I was hoping this would be something relatively simple that I could set up, but if not that's fine.

Thanks for getting back to me quickly!
