### ISSUE TITLE
Detailed power information

### ISSUE THREAD

**Issue by DevTechProfile** [falahati/NvAPIWrapper#25]
HWiNFO now supports Detailed power information.

![grafik](https://user-images.githubusercontent.com/30285858/82722794-10f46380-9cca-11ea-8a8b-c5e17cacbe85.png)

Any plans to implement that?

**Comment by MaynardMiner** [comment]
They are likely using NVML, which can detailed information such as this. That would require an entirely new (And freakishly huge) wrapper.

**Comment by MaynardMiner** [comment]
https://docs.nvidia.com/deploy/nvml-api/group__nvmlUnitQueries.html#group__nvmlUnitQueries_1ga1b4882799bffff6ea3e14b043061df5

They can retrieve the power state of each unit in device with API.
