### ISSUE TITLE
Doesnt work with 4.7?

### ISSUE THREAD

**Issue by ssshake** [falahati/NvAPIWrapper#3]
Just pulled down your project unmodified and upon build I get this.

```

Build started ...
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. 
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by falahati** [comment]
I have no problem with my system while rebuilding it with VS2017 or VS2015 or the build script (tested with both .net4.5 and .net4.7). However, the project was initially created in VS2015 and I still have it installed on the system. And the build script probably uses MSBUILD14, so if you failed to build it with the build script, simply try opening the solution and rebuild it with VS directly.

**Comment by ssshake** [comment]
HI I dont know how to do that but I will give it a shot

**Comment by falahati** [comment]
Closed due to inactivity
