### ISSUE TITLE
GTX cards fan issue

### ISSUE THREAD

**Issue by MaynardMiner** [falahati/NvAPIWrapper#30]
So I have user that was using my software with your wrapper with no issues. He has 3 GTX 1080ti cards.

This user decided to do a bios update on the cards. Upon doing a bios update, he noticed in EVGA precision (EVGA's overclocking software) now has the option to set both fans individually. It works correctly. Prior to the bios update, only 1 fan could be set.

Using the wrapper:

``CoolerInformation.Coolers``

The cards only return 1 fan cooler still.

I wasn't even aware that any GTX cards could be dual-fan aware. This is news to me. The user confirmed that he can now set fans individually after bios update.

This is a photo which uses the simple software I have made, along with the EVGA precision showing the card's fan speeds. Both this user and myself can set RTX dual-fan aware cards with the software. GTX cards however are failing due to only one cooler being found.

Do you have any ideas?

![image](https://user-images.githubusercontent.com/38481606/88877928-a7766100-d1f4-11ea-9525-544de5696635.png)

**Comment by MaynardMiner** [comment]
```
            NVIDIA.Initialize();
            var GPUs = PhysicalGPU.GetPhysicalGPUs();
            var Count = GPUs.Count();
                // Change speed if applicable
                if (Speed > -1)
                {
                    var Cool = GPUs[Index].CoolerInformation.Coolers;
                    Console.WriteLine("Current Fan Speed: " + GPUs[Index].CoolerInformation.CurrentFanSpeedLevel);
                    foreach (GPUCooler cooler in Cool)
                    {
                        Console.WriteLine("Current Fan Speed For Cooler " + cooler.CoolerId + ":" + GPUs[Index].CoolerInformation.CurrentFanSpeedLevel);
                        GPUs[Index].CoolerInformation.SetCoolerSettings(cooler.CoolerId, Speed);
                    }
                    Console.WriteLine("New Fan Speed: " + Speed);
                }
```

Code snippet from software.
Variable ``Speed`` and ``Index`` are arguments

**Comment by MaynardMiner** [comment]
The only thing I could think of, is maybe ``Coolertarget.All`` may have an additional target with bios besides just ``GPU`` ``Memory`` and ``Bios`` in CoolerTarget.cs

**Comment by MaynardMiner** [comment]
```
        public IEnumerable<GPUCooler> Coolers
        {
            get
            {
                /// There are two different methods.
                /// The first one is the current method, and works
                /// for dual fan aware cards.
                /// This should be tested first. If it returns
                /// NVAPI_NOT_SUPPORTED, then the old V1 method is
                /// ran.
  
                PrivateFanCoolersStatusV1? status = null;
                PrivateFanCoolersInfoV1? info = null;
                PrivateFanCoolersControlV1? control = null;

                try
                {
                    status = GPUApi.GetClientFanCoolersStatus(PhysicalGPU.Handle);
                    info = GPUApi.GetClientFanCoolersInfo(PhysicalGPU.Handle);
                    control = GPUApi.GetClientFanCoolersControl(PhysicalGPU.Handle);
                }
                catch (NVIDIAApiException e)
                {
                    if (e.Status != Status.NotSupported)
                    {
                        throw;
                    }
                }

                if (status != null && info != null && control != null)
                {
                    for (var i = 0; i < status.Value.FanCoolersStatusEntries.Length; i++)
                    {
                        if (info.Value.FanCoolersInfoEntries.Length > i &&
                            control.Value.FanCoolersControlEntries.Length > i)
                        {
                            yield return new GPUCooler(
                                info.Value.FanCoolersInfoEntries[i],
                                status.Value.FanCoolersStatusEntries[i],
                                control.Value.FanCoolersControlEntries[i]
                            );
                        }
                    }

                    yield break;
                }


                PrivateCoolerSettingsV1? settings = null;
                try
                {
                    settings = GPUApi.GetCoolerSettings(PhysicalGPU.Handle);
                }
                catch (NVIDIAApiException e)
                {
                    if (e.Status != Status.NotSupported)
                    {
                        throw;
                    }
                }

                if (settings != null)
                {
                    for (var i = 0; i < settings.Value.CoolerSettings.Length; i++)
                    {
                        if (i == 0)
                        {
                            var currentRPM = -1;
                            try
                            {
                                currentRPM = (int)GPUApi.GetTachReading(PhysicalGPU.Handle);
                            }
                            catch (NVIDIAApiException)
                            {
                                // ignored
                            }

                            if (currentRPM >= 0)
                            {
                                yield return new GPUCooler(
                                    i,
                                    settings.Value.CoolerSettings[i],
                                    currentRPM
                                );
                                continue;
                            }
                        }

                        yield return new GPUCooler(
                            i,
                            settings.Value.CoolerSettings[i]
                        );
                    }

                    yield break;
                }

                throw new NVIDIAApiException(Status.NotSupported);
            }
        }
```

Fixes I believe. I'm trying to get more users to test to confirm their is no issues, but I have received none.

I currently have a machine that has cards in which only the old version works, and cards in which only the new version works. It doesn't matter that it's flipped around: The older GTX cards will throw a NVAPI_NOT_SUPPORTED, and then do the old version API. But cards that have support both API methods needs to do v2 first it seems.

**Comment by falahati** [comment]
@MaynardMiner, Hey, I got an email regarding a solution to this and but comment is missing. Was it wrong?

**Comment by MaynardMiner** [comment]
"So I have user that was using my software with your wrapper with no issues. He has 3 GTX 1080ti cards.

This user decided to do a bios update on the cards. Upon doing a bios update, he noticed in EVGA precision (EVGA's overclocking software) now has the option to set both fans individually. It works correctly. Prior to the bios update, only 1 fan could be set.

Using the wrapper:

CoolerInformation.Coolers

The cards only return 1 fan cooler still.

I wasn't even aware that any GTX cards could be dual-fan aware. This is news to me. The user confirmed that he can now set fans individually after bios update.

This is a photo which uses the simple software I have made, along with the EVGA precision showing the card's fan speeds. Both this user and myself can set RTX dual-fan aware cards with the software. GTX cards however are failing due to only one cooler being found.

Do you have any ideas?"

I have tried to Flip around methods in ``GPUCooler``. Have it run the new api first for RTX, then run the old one. I thought maybe that the bios update allowed the new one to work. I confirmed that the RTX version of fan setting didn't work at all. Just the original, but it sets only the first fan.

I think the original version you made seems to only returns 1 cooler by default. Is there a way to have the old version check for multiple coolers?

**Comment by MaynardMiner** [comment]
I thought I solved it, but was wrong.

**Comment by MaynardMiner** [comment]
Later tonight, I was going to try to have it run:

```
                    status = GPUApi.GetClientFanCoolersStatus(PhysicalGPU.Handle);
                    info = GPUApi.GetClientFanCoolersInfo(PhysicalGPU.Handle);
                    control = GPUApi.GetClientFanCoolersControl(PhysicalGPU.Handle);
```

Each individually instead of a ```try{} catch{}`` for all three, to see if one in particular is failing. I mean if v1 is working, the only one that is needed is ``status`` I believe to get the cooler count if I'm reading it right. The rest of the information can be pulled from the successful v1 method (it works with the bios update).

I will report when I get the user to test it.

**Comment by falahati** [comment]
Well, `PrivateCoolerSettingsV1` supports multiple cooler information. So it should work and since it doesn't, there is probably another problem somewhere. You can try the low-level API `GPUApi.GetCoolerSettings()` and see what it really returns. You can also forcefully run `GPUApi.SetCoolerLevels()` with a greater cooler id, if this is the real method used by other software, it should be able to change the speed.

Is there any open-source program that shows you both fans? As of now, I can't think of a way to solve it except maybe diving into debugging AfterBurner again, but since this isn't even your card and you can't really help with that and the fact that I don't even own a 10xx GPU let alone a duel fan one, I can't do much for this except maybe keeping the issue open for later.

**Comment by MaynardMiner** [comment]
I have been searching for software outside of your that will show both fans. I haven't found any as of yet, besides linux ``nvidia-settings`` 

I will see what GPUAPI.GetCoolerSettings() returns.

I will try to forcefully run GPUApi.SetCoolerLevels().

I plan to continue trying to solve. This has been the only software that has worked thus far as it has.

**Comment by MaynardMiner** [comment]
Just an update:

I don't think NVAPI is being used for their controller. I had him try multiple monitoring software like ``openharwaremonitor`` which is open source C# as well as some C programs that worked for me, but not for him.

Nvapi is only returning 1 cooler for that software as well. Only thing that works is manufacturer software for his cards. It must be the bios the user upgraded to.

Everything low level is returning one 1 fan cooler, I made some debug software that would output values as it running the lower level API...And it one returns a count of 1 and 1 coolersetting.

I'm going to close this, I think it is the after production manufacturer bios that is cause.
