### ISSUE TITLE
Unable to load shared library 'nvapi64' or one of its dependencies

### ISSUE THREAD

**Issue by rwecho** [falahati/NvAPIWrapper#32]
Can not work in ubuntu. 

``` csharp
  var physicalGpuList = NvAPIWrapper.GPU.PhysicalGPU.GetPhysicalGPUs();
```

Is this library ready to support the Linux platform? 
thanks.

**Comment by falahati** [comment]
This is a wrapper for NVAPI library. NVAPI is not supported or available in Linux.

https://www.reddit.com/r/linux_gaming/comments/9kprig/why_nvidia_does_not_release_nvapi_for_linux/
