### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by rom4ster** [falahati/NvAPIWrapper#36]
I downloaded the package from NUGET and no write I2C functions are available

**Comment by rom4ster** [comment]
Yeah really... ok so the I2C stuff I am looking for was literally added A DAY after the latest NUGET release... -_-

**Comment by falahati** [comment]
https://github.com/falahati/NvAPIWrapper/releases/tag/v0.8.1.101

sry, I was expecting more changes to aggregate and release a new version but never found the time.
