### ISSUE TITLE
[Help wanted] Is there a way to check if the GPU supports vulkan?

### ISSUE THREAD

**Issue by ClonkAndre** [falahati/NvAPIWrapper#39]
I would like to know if this is possible with this lib :)
And if there is a way, how could i check for vulkan support?

**Comment by MaynardMiner** [comment]
`vulkaninfo` is a command that can be ran from console, and will give you details on vulkan compatibility. Could run as a process, and capture output.

Vulkan is separate of NVIDIA, and will not be in the NVAPI lib.

**Comment by MaynardMiner** [comment]
https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/struct__NV__LOGICAL__GPU__DATA__V1.html

Vulkan deviceNodeMask in VkPhysicalDeviceIDProperties

http://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceProperties.html

VkPhysicalDeviceProperties would give physical device properties, but I'm unsure if that means its supported.
