### ISSUE TITLE
Question about optimus

### ISSUE THREAD

**Issue by ssshake** [falahati/NvAPIWrapper#4]
Probably not the appropriate place to ask this but you are more familiar with the nvidia library than me. 

Could I use this to do three things.

1) Determine if my GPU is currently nvidia or intel
2) Get the GPU utilization
3) Iterate over all of my apps and force them to use nvidia GPU (such as can be done manually in the nvidia control panel)

Any direction would be appreciated, thanks.

**Comment by falahati** [comment]
Hey,

1. What do you mean by that? In an Optimus environment, you are going to have them both active at any given moment. As far as I know, only the game running on the system knows if it got an Intel context or a nVidia one.

2. Currently, the library is able to provide you with basic resource utilization values thanks to @Draiget commits. These values are available at "PhysicalGPU.DynamicPerformanceStatesInfo" property.

However, it is by no means complete. If you are interested in implementing these functionalities to their fullest, following documentation can help you:
https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__gpuapi.html

3. This part of the NvAPI (DRS - Driver Settings) is not yet implemented in any part (as mentioned in the readme). However, again, if you are interested in contributing to the project, following documentation is a good starting point:
https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__drsapi.html
