### ISSUE TITLE
using vs2017 open last sln but show error 

### ISSUE THREAD

**Issue by fingerx** [falahati/NvAPIWrapper#42]
![image](https://user-images.githubusercontent.com/5524551/114820982-75dd0e80-9df2-11eb-8f7d-5d2c25db31ca.png)

hi,dont knwo why,need your help,thanks

**Comment by falahati** [comment]
No idea; please make sure that you have no modified file. I am doing my development on VS219 currently but I don't remember if I was on VS 2017 at the time or not.

**Comment by fingerx** [comment]
@falahati  thanks
