### ISSUE TITLE
Mosaic API calls returning NVAPI_NOT_SUPPORTED exception

### ISSUE THREAD

**Issue by omergulzar2** [falahati/NvAPIWrapper#43]
I have NVS 510 card. I am able to set my displays in mosaic configuration using NVidia control panel. But when i try to get the current topology using this call

`MosaicApi.GetCurrentTopology(out TopologyBrief tb, out IDisplaySettings ds, out int x, out int y);`

It returns NVAPI_NOT_SUPPORTED exception. I tried a few more methods like 'MosaicApi.GetSupportedTopologiesInfo' but everything return the same exception.

**Comment by falahati** [comment]
try using the higher-level API that is there to do so (`NvAPIWrapper.Mosaic` namespace especially the `GridTopology` class and other related types). Mosaic has two different API levels, one might not be supported. I should remove the older API altogether. Grid topology is the one you need to use I believe.

You can also check out the source code of this project to see how this can be done properly:
https://github.com/falahati/HeliosDisplayManagement/

**Comment by omergulzar2** [comment]
Thanks for pointint me in the right direction. I was trying to change resolution of mosaic and it worked through GridTopology.

Thanks
