### ISSUE TITLE
Detecting GPU presence when running inside cloud VM

### ISSUE THREAD

**Issue by afarley-tangent** [falahati/NvAPIWrapper#5]
Hi,

I'm using your library to detect GPU presence, and fall back to CPU if necessary. On Windows Server VMs (tested AWS, Azure and Alibaba cloud) with nVidia GPUs, this library returns NVAPI_NVIDIA_DEVICE_NOT_FOUND.

Locally, this library correctly detects the presence of GTX and Quadro-series GPUs. Are you aware of any reason that this library would fail to detect GPU presence for a cloud VM? Is there a feasible work-around?

**Comment by falahati** [comment]
I have no idea about this issue. In fact, I never tried to run it under any virtual machine.

I assume you are running windows on these systems. Can you double check if you can, in fact, install Nvidia Drivers and open Nvidia control panel? What do you get from running tools like GPU-Z?

Please keep in mind that this tool is only a wrapper over the official Nvidia API library known as NVAPI and therefore it can't and won't try to do anything not already implemented or extra to what NVAPI does in any way.

Also if you are only interested in detecting NVidia GPU presence, would you try the other library that I made for calling windows CCD APIs?
https://github.com/falahati/WindowsDisplayAPI

**Comment by falahati** [comment]
Closed due to inactivity.
