### ISSUE TITLE
Available settings by display

### ISSUE THREAD

**Issue by yoyos** [falahati/NvAPIWrapper#54]
Hello,

Thanks for the good work.

I'm trying to help implement something but how would you implement a method to retrieve all available settings by display ?

Like all resolutions available, all refreshrates available, etc..

is there a NvApi methods to do that we can wrap ?

Thank you !

![image](https://user-images.githubusercontent.com/1993859/145225255-984534e7-fc17-485f-bed7-53fdc7316d72.png)

**Comment by falahati** [comment]
this is not yet added to my [WindowsDisplayAPI](https://github.com/falahati/WindowsDisplayAPI/); there are functions to get the preferred signal info but I don't remember having anything to return a list of possible timings; neither do I remember having something similar in the NVAPI and therefore this wrapper.

My [EDIDParser](https://github.com/falahati/EDIDParser/) library tho can extract this information from the connected display;

**Comment by yoyos** [comment]
Thanks for your help

Do you have a sample of code to parse a raw EDID binary data coming from NvApiWrapper ?
Or is it working only with your WindowsDisplayAPI ?

**Comment by falahati** [comment]
each library has a `Sample` project.

`EDIDParser` can be used with both libraries and there are samples for both.
https://github.com/falahati/EDIDParser/blob/master/EDIDParserSample/Program.cs
