### ISSUE TITLE
Scale and layout settings

### ISSUE THREAD

**Issue by yoyos** [falahati/NvAPIWrapper#55]
Hello,

How would you implement something that could retrieve scaling factor by display ?

I would like at least get the selected % from this list for each display : 

![image](https://user-images.githubusercontent.com/1993859/145225633-04734832-3622-4311-b4e0-0198ceb7ed4d.png)

Thanks

**Comment by falahati** [comment]
This is unrelated to NVIDIA API, however, it is included in my other library.

This exact commit in the "WindowsDisplayAPI" library added this feature:
https://github.com/falahati/WindowsDisplayAPI/commit/f050ad7b42ae30e1d58b5d69605172c324eebae4
