### ISSUE TITLE
Recent nvidia GPU fans aren't able to be controlled

### ISSUE THREAD

**Issue by Banapple01** [falahati/NvAPIWrapper#58]
https://github.com/Rem0o/FanControl.Releases
This fan controlling software which uses your wrapper is unable to effect fan speeds or controls for the recent nvidia graphics cards.
I'm using a 6800
![2022-04-23_LI](https://user-images.githubusercontent.com/48165909/164912301-fa91713c-85ab-4476-856e-401f3c98ea3b.jpg)

**Comment by falahati** [comment]
how recent are we talking about? any specific model? what is the error?
I need more info

**Comment by falahati** [comment]
6800 is an ATI card, this is an NVidia-only library

**Comment by Banapple01** [comment]
Woops, sorry. I totally mixed up amd and nvidia. I'll get rid of this post
