### ISSUE TITLE
per process usage?

### ISSUE THREAD

**Issue by tigros** [falahati/NvAPIWrapper#65]
I'm looking for an easy way to get GPU memory/usage for a given process, that also works on windows 7, in C#. If not with nvapi.dll then what? I guess I could use the output from nvidia-smi for now but it's strange that it's not easier, with some C# lib.

Edit: Even nvidia-smi shows N/A for memory on Windows 7, oh well, D3DKMTQueryStatistics looks promising.

**Comment by tigros** [comment]
maybe this wasn't such a good place to ask about this, anyway if anyone needs it i upped some code to https://github.com/tigros/GPUmembyproc

**Comment by falahati** [comment]
sry for the late response.

No, unfortunately I am not aware of any method in NVAPI that provides such information. I know nvidia-smi shows the usage, but I am not aware if memory usage is accurate or not.
