### ISSUE TITLE
Change DSR Smoothnes factor

### ISSUE THREAD

**Issue by SelimNazar** [falahati/NvAPIWrapper#67]
Can this library be used to modify the DSR Smoothness factor from the Nvidia control panel? My objective is to write an script that lets me set this value before a game starts, as a way to have different factors per game. This would allow me to use both 4x DSR and 2.25x DLDSR without having to manually change the Smoothnes from 0% to 100%, since Nvidia can't be bothered to add this functionality themselves.

**Comment by falahati** [comment]
where is this setting located? if it is on the game profile page, you should look into the DRS config. might have to pass an undocumented setting id to get or modify these settings.
