### ISSUE TITLE
Which API can I use to modify the brightness, I can't seem to find it, can someone tell me? Thanks!~~~

### ISSUE THREAD

**Issue by tianyixin** [falahati/NvAPIWrapper#69]
![PixPin_2023-12-01_11-18-18](https://github.com/falahati/NvAPIWrapper/assets/16138004/6b874351-1b66-4a48-ad0b-bbe4e248df24)

**Comment by falahati** [comment]
this is the color profile modification page. I don't remember it being a part of the NvAPI

**Comment by falahati** [comment]
but you can always check the NvAPI native API documentation here:
https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/index.html

**Comment by falahati** [comment]
#20

**Comment by tianyixin** [comment]
oh thanks! I'm going to study

**Comment by tianyixin** [comment]
thannnnnnks!
