### ISSUE TITLE
Convert frequency from kHz to mHz

### ISSUE THREAD

**Issue by OudomMunint** [falahati/NvAPIWrapper#70]
How do I convert frequency from kHz to mHz, I'm getting clockspeeds for gpu core and vram but they are printed in kHz and I can't divide them by 1000

**Comment by falahati** [comment]
please post a sample code. and why cant you divide them by 1k? I don't understand that part.

**Comment by OudomMunint** [comment]
@falahati it my bad,
I tried to do `Console.WriteLine("Core Clock: {0}", gpu.BoostClockFrequencies.GraphicsClock.Frequency) / 1000` or something to that extent.
It got around it by doing:
`var graphicsClockKHz = gpu.BoostClockFrequencies.GraphicsClock.Frequency;`
`var graphicsClockMHz = graphicsClockKHz / 1000;`
`Console.WriteLine("GPU Core Speed: {0} MHz", graphicsClockMHz);`

On a side note is there a flag to detect if GPU is integrated or dedicated? It used to be simple but since Intel now has dedicated gpus and amd has integrated GPUs it's gotten quite tricky

**Comment by falahati** [comment]
Yes, `PhysicalGPU.GPUType == GPUType.Discret`

**Comment by OudomMunint** [comment]
@falahati Thanks I'm able to use it to filter GPUs. Thanks!
![image](https://github.com/falahati/NvAPIWrapper/assets/108245473/3f3429e2-a47c-47fc-ad4d-5321d57b76e9)
