### ISSUE TITLE
Setting Position and Resolution of Screens

### ISSUE THREAD

**Issue by srb1986** [falahati/NvAPIWrapper#8]
Amazing application, just the thing I was looking for!

Any chance you could provide an example of setting of properties within your sample code, at the moment, there is only getting of properties.

I want to change the resolution and/or positions of screens dynamically within a 3 screen system and wondered if this would be possible using this wrapper.  

I've tried modifying properties, e.g. IsGDIPrimary, Position, Resolution within the PathInfo class however I'm not seeing any effect.

Many thanks again for the fantastic app.

S

**Comment by falahati** [comment]
Hey Steven,

First, you need to create an array of `PathInfo` instances for the configurations you want. Keep in mind that each `PathInfo` represents a logical display and each contains one or more physical displays that are configured and recognized by a `PathTargetInfo` instance (accessible from the `PathInfo.TargetsInfo` property as an array) - these physical displays are cloned and all going to show the same output as they all representations of one logical display.

After creating a `PathInfo` for each logical display and configured its properties including all physical display represented by `PathTargetInfo` instances, you need to ask NVidia Driver to try to apply this configuration by calling `PathInfo.SetDisplaysConfig()` **static** method.

You also take the currently active configuration using the `PathInfo.GetDisplaysConfig()` static method and change it to your liking and then apply it.

To change the display profile, however, I don't actually recommend using this library as it is limited to NVidia GPUs, following repo contains the code that allows you to easily change display settings for any brand of GPU using Windows API (API is very similar to this, you are going to still have `PathInfo` and `PathTargetInfo`, the only significant difference is a specific class for logical displays named `PathSourceInfo` and therefore `PathInfo` acts as more of a connection between these two):

https://github.com/falahati/WindowsDisplayAPI/

You can also check the source code of the following program as a better and more complete sample (comparing to the sample project included in this repo) for both this library and the WindowsDisplayAPI library:

https://github.com/falahati/HeliosDisplayManagement

**Comment by srb1986** [comment]
Wow thanks for the detailed reply.  I will try those suggestions asap.  You have a great set of tools here. 👍
